version: "3.8"

services:
  postgres:
    image: postgres:alpine3.17
    container_name: e-holter-be-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "${POSTGRES_PORT}:5432"
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:8.1
    container_name: e-holter-be-pgadmin
    ports:
    - "8888:80"
    volumes:
    - admin_data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres
      
volumes:
  db_data:
  admin_data:

networks:
  default:
    name: be-net
    driver: bridge
